DELIMITER $$
DROP PROCEDURE IF EXISTS recorrer_meses $$
CREATE PROCEDURE recorrer_meses()
BEGIN

/* DECLARACION DE VARIABLES */
DECLARE lrf BOOL;
DECLARE cuantos, v1, b1 INT;

/* DECLARAMOS EL CURSOR */
DECLARE cursor1 CURSOR FOR
SELECT id
FROM cuentas;

/* DECLARAMOS EL CONTROL DE ERRORES */
DECLARE CONTINUE HANDLER FOR NOT FOUND SET lrf = 1;


bucle: LOOP
FETCH cursor1 INTO vcodigo
	IF lrf = 1
		THEN LEAVE bucle;
	END IF;
END LOOP;



END; $$
DELIMITER ;
